server:
   port:8080

spring:
    jpa:
      open-in-view: false
      show-sql: true
    h2:
     console:
        enabled: true
        path: /h2-console
    datasource:
 #      url: jdbc:h2:mem:testdb
       url: jdbc:h2:~/test
    output:
        ansi:
          enabled: ALWAYS

logging:
    level:
        com.openclassrooms: DEBUG
    file: watchlist-app.log

info:
   name: Watchlist
   description: OpenClassRoom Tutorial-SpringBoot-3tier, DI,Logging and Monitoring
   version: 1.0
   
management:
    endpoints:
            web:
              exposure:
                   include: info,health,beans,env,metrics,release-notes   